services:
  back:
    build: ./back
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - ./back:/var/www
    environment:
      DATABASE_URL: mysql://melwin:duquenne@db:3306/roomies
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - roomisnet

  frontend:
    build: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - roomisnet

  websocket:
    build: ./wb
    container_name: websocket_server
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ./wb:/app
    networks:
      - roomisnet

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: roomies
      MYSQL_USER: melwin
      MYSQL_PASSWORD: duquenne
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "3306:3306"
    networks:
      - roomisnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8321:80"
    depends_on:
      - db
    networks:
      - roomisnet

  mongodb:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - roomisnet

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - roomisnet

volumes:
  db_data:
  mongo_data:

networks:
  roomisnet:
    driver: bridge
